### ISSUE TITLE
When is distributed proving coming?

### ISSUE THREAD

**Issue by matthiasgoergens** [facebook/winterfell#137]
Our [README](https://github.com/facebook/winterfell/blob/main/README.md) says:

> Therefore, our final goal is to efficiently distribute proof generation across many machines.

What's the current status of distributed proving?  What are the plans?

**Comment by irakliyk** [comment]
With recursive proofs being quite efficient nowadays, distributing proof generation across multiple machines can be done better with recursion. Specifically, instead of trying to generate one big proof spread over multiple machines, it would probably be much more efficient to generate smaller proofs on each machine, and then aggregate them using recursion.

So, distributing generation of one large proof across multiple machines is not actively being worked on at the moment.

**Comment by alpom13** [comment]
@irakliyk Are you aware of a STARK implementation (VM or EDSL or ...) based on Winterfell that actually supports recursive proof verification today?

**Comment by irakliyk** [comment]
No - all current release of Winterfell don't allow using airthmetization-friendly hash functions during proof generation - this makes recursive proofs impractical. But the code currently in the `main` branch allows users to use any hash function. So, with the next release of Winterfell (hopefully in about a week), it would be possible to use it for recursive proofs.

**Comment by matthiasgoergens** [comment]
Thanks for explaining!

Is the current release of Winterfell now more recursion friendly?

**Comment by irakliyk** [comment]
Yes - recursion is fully supported now. In fact, this is already used in [Miden VM](https://github.com/0xPolygonMiden/miden-vm/blob/next/miden/src/cli/prove.rs#L34).

**Comment by matthiasgoergens** [comment]
Awesome, thanks!
